// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutpatientClinicsComplex.Models;

#nullable disable

namespace OutpatientClinicsComplex.Migrations
{
    [DbContext(typeof(OutpatientClinicsComplexContext))]
    [Migration("20260618150834_adddatabase")]
    partial class adddatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorCode")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15);

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<long?>("PatientNationalId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ReceptionistCode")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Appointm__3214EC07C9AE0B6D");

                    b.HasIndex("DoctorCode");

                    b.HasIndex("ReceptionistCode");

                    b.HasIndex("PatientId", "PatientNationalId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.DangerousDisease", b =>
                {
                    b.Property<string>("DiseaseName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DiseaseName");

                    b.ToTable("DangerousDiseases", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Diagnosis");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DoctorCode")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsDangerous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsReported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("LabConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id", "NationalId");

                    b.HasIndex("DoctorCode");

                    b.ToTable("Diagnosis", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Doctor", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code")
                        .HasName("PK__Doctor__A25C5AA64F0D0F84");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.LabTechnician", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code")
                        .HasName("PK__LabTechn__A25C5AA6D6A07C33");

                    b.ToTable("LabTechnician", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.OutbreakLimit", b =>
                {
                    b.Property<string>("Diagnosis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.HasKey("Diagnosis");

                    b.ToTable("OutbreakLimits", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.PatientHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorCode")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReceptionistCode")
                        .HasColumnType("int");

                    b.HasKey("Id", "NationalId")
                        .HasName("PK_Patient");

                    b.HasIndex("DoctorCode");

                    b.HasIndex("ReceptionistCode");

                    b.ToTable("PatientHistory", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Pharmacist", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code")
                        .HasName("PK__Pharmaci__A25C5AA672ADC5DF");

                    b.ToTable("Pharmacist", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int>("DoctorCode")
                        .HasColumnType("int");

                    b.Property<string>("Medicines")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PharmacistCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "NationalId");

                    b.HasIndex("DoctorCode");

                    b.HasIndex("PharmacistCode");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Receptionist", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code")
                        .HasName("PK__Receptio__A25C5AA604D7A5A4");

                    b.ToTable("Receptionist", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.ReportSetting", b =>
                {
                    b.Property<string>("ReportType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Limit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportType", "Diagnosis");

                    b.ToTable("ReportSettings", (string)null);
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.RequiredTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DoctorCode")
                        .HasColumnType("int");

                    b.Property<int?>("LabTechnicianCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RequiredTests")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "NationalId");

                    b.HasIndex("DoctorCode");

                    b.HasIndex("LabTechnicianCode");

                    b.ToTable("RequiredTests");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LabTechnicianCode")
                        .HasColumnType("int");

                    b.Property<int>("RequiredTestId")
                        .HasColumnType("int");

                    b.Property<string>("ResultTests")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id", "NationalId");

                    b.HasIndex("LabTechnicianCode");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Appointment", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.Doctor", "DoctorCodeNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorCode")
                        .HasConstraintName("FK_Appointment_Doctor");

                    b.HasOne("OutpatientClinicsComplex.Models.Receptionist", "ReceptionistCodeNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("ReceptionistCode")
                        .HasConstraintName("FK_Appointment_Receptionist");

                    b.HasOne("OutpatientClinicsComplex.Models.PatientHistory", "PatientHistory")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId", "PatientNationalId")
                        .HasConstraintName("FK_Appointment_Patient");

                    b.Navigation("DoctorCodeNavigation");

                    b.Navigation("PatientHistory");

                    b.Navigation("ReceptionistCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Diagnosis", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.Doctor", "DoctorCodeNavigation")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DoctorCode")
                        .HasConstraintName("FK_Diagnosis_Doctor");

                    b.Navigation("DoctorCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.PatientHistory", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.Doctor", "DoctorCodeNavigation")
                        .WithMany("PatientHistories")
                        .HasForeignKey("DoctorCode")
                        .HasConstraintName("FK_Patient_Doctor");

                    b.HasOne("OutpatientClinicsComplex.Models.Receptionist", "ReceptionistCodeNavigation")
                        .WithMany("PatientHistories")
                        .HasForeignKey("ReceptionistCode")
                        .HasConstraintName("FK_Patient_Receptionist");

                    b.Navigation("DoctorCodeNavigation");

                    b.Navigation("ReceptionistCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Prescription", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.Doctor", "DoctorCodeNavigation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorCode")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Doctor");

                    b.HasOne("OutpatientClinicsComplex.Models.Pharmacist", "PharmacistCodeNavigation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacistCode")
                        .HasConstraintName("FK_Prescription_Pharmacist");

                    b.Navigation("DoctorCodeNavigation");

                    b.Navigation("PharmacistCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.RequiredTest", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.Doctor", "DoctorCodeNavigation")
                        .WithMany("RequiredTests")
                        .HasForeignKey("DoctorCode")
                        .HasConstraintName("FK_RequiredTests_Doctor");

                    b.HasOne("OutpatientClinicsComplex.Models.LabTechnician", "LabTechnicianCodeNavigation")
                        .WithMany("RequiredTests")
                        .HasForeignKey("LabTechnicianCode")
                        .HasConstraintName("FK_RequiredTests_LabTechnician");

                    b.Navigation("DoctorCodeNavigation");

                    b.Navigation("LabTechnicianCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.TestResult", b =>
                {
                    b.HasOne("OutpatientClinicsComplex.Models.LabTechnician", "LabTechnicianCodeNavigation")
                        .WithMany("TestResults")
                        .HasForeignKey("LabTechnicianCode")
                        .HasConstraintName("FK_TestResults_LabTechnician");

                    b.Navigation("LabTechnicianCodeNavigation");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Diagnoses");

                    b.Navigation("PatientHistories");

                    b.Navigation("Prescriptions");

                    b.Navigation("RequiredTests");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.LabTechnician", b =>
                {
                    b.Navigation("RequiredTests");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.PatientHistory", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Pharmacist", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("OutpatientClinicsComplex.Models.Receptionist", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PatientHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
